"""
POST /tools/generate-file  (contract §2.6 / §2.7a)

Turns the contract's simple `content` shape:
    { "title": str, "sections": [ { "heading": str, "body": str }, ... ] }
into a real .docx / .xlsx / .pptx file written under the shared FILES_DIR,
and returns a *path* (never a localhost:8001 URL) per §2.7a.

Kept deliberately simple per §2.6: "Keep `content` exactly this simple. If a
task needs more, flag it to the team — don't extend the schema solo."
"""
import re
import uuid
from pathlib import Path

from docx import Document
from docx.shared import Pt

from openpyxl import Workbook
from openpyxl.styles import Font

from pptx import Presentation
from pptx.util import Inches, Pt as PptPt

from .config import FILES_DIR


class UnsupportedFileType(Exception):
    pass


def _safe_slug(title: str) -> str:
    slug = re.sub(r"[^a-zA-Z0-9\-]+", "-", title.strip().lower()).strip("-")
    return slug[:40] or "document"


def _new_filename(title: str, ext: str) -> str:
    return f"{uuid.uuid4().hex[:8]}-{_safe_slug(title)}.{ext}"


def _generate_docx(content: dict, out_path: Path):
    title = content.get("title", "Untitled")
    sections = content.get("sections", [])

    doc = Document()
    heading = doc.add_heading(title, level=0)

    for section in sections:
        sec_heading = section.get("heading", "")
        sec_body = section.get("body", "")
        if sec_heading:
            doc.add_heading(sec_heading, level=1)
        if sec_body:
            for para_text in sec_body.split("\n"):
                if para_text.strip():
                    p = doc.add_paragraph(para_text)
                    p.style.font.size = Pt(11)

    doc.save(out_path)


def _generate_xlsx(content: dict, out_path: Path):
    title = content.get("title", "Untitled")
    sections = content.get("sections", [])

    wb = Workbook()
    ws = wb.active
    ws.title = "Sheet1"

    ws["A1"] = title
    ws["A1"].font = Font(size=14, bold=True)

    row = 3
    for section in sections:
        sec_heading = section.get("heading", "")
        sec_body = section.get("body", "")
        if sec_heading:
            cell = ws.cell(row=row, column=1, value=sec_heading)
            cell.font = Font(bold=True)
            row += 1
        if sec_body:
            for line in sec_body.split("\n"):
                if line.strip():
                    ws.cell(row=row, column=1, value=line)
                    row += 1
        row += 1  # blank spacer row between sections

    ws.column_dimensions["A"].width = 100
    wb.save(out_path)


def _generate_pptx(content: dict, out_path: Path):
    title = content.get("title", "Untitled")
    sections = content.get("sections", [])

    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    title_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_layout)
    slide.shapes.title.text = title
    if len(slide.placeholders) > 1:
        slide.placeholders[1].text = "Generated by Sovereign On-Premise AI Workbench"

    body_layout = prs.slide_layouts[1]
    for section in sections:
        sec_heading = section.get("heading", "")
        sec_body = section.get("body", "")
        slide = prs.slides.add_slide(body_layout)
        slide.shapes.title.text = sec_heading or " "
        body_placeholder = slide.placeholders[1]
        tf = body_placeholder.text_frame
        tf.clear()
        lines = [l for l in sec_body.split("\n") if l.strip()] or [""]
        tf.text = lines[0]
        tf.paragraphs[0].font.size = PptPt(18)
        for line in lines[1:]:
            p = tf.add_paragraph()
            p.text = line
            p.font.size = PptPt(18)

    prs.save(out_path)


_GENERATORS = {
    "docx": _generate_docx,
    "xlsx": _generate_xlsx,
    "pptx": _generate_pptx,
}


def generate_file(file_type: str, content: dict) -> dict:
    """
    Returns: {"file_url": "/files/<name>", "file_name": "<name>"}
    Raises UnsupportedFileType for anything other than docx/xlsx/pptx.
    """
    if file_type not in _GENERATORS:
        raise UnsupportedFileType(f"Unsupported file type: {file_type!r}")

    title = content.get("title", "Untitled")
    filename = _new_filename(title, file_type)
    out_path = FILES_DIR / filename

    _GENERATORS[file_type](content, out_path)

    return {
        "file_url": f"/files/{filename}",
        "file_name": filename,
    }
